version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: "mes"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "****"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - '54320:5432'
    volumes:
      - ./migrations/chats.sql:/docker-entrypoint-initdb.d/bchats.sql
      - ./migrations/messages.sql:/docker-entrypoint-initdb.d/cmessages.sql
      - ./migrations/user.sql:/docker-entrypoint-initdb.d/auser.sql
  app:
    image: tsapp
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
volumes:
  db:
    driver: local